export const PROFILE_SETTINGS = [
  {
    id: "profileEmail",
    name: "email",
    label: "Почта",
    placeholder: "Введите адрес",
    type: "text",
    required: true,
    disabled: true,
    error: "",
  },
  {
    id: "profileLogin",
    name: "login",
    label: "Логин",
    placeholder: "Введите логин",
    type: "text",
    required: true,
    disabled: true,
    error: "",
  },
  {
    id: "profileFirstName",
    name: "first_name",
    label: "Имя",
    placeholder: "Введите имя",
    type: "text",
    required: true,
    disabled: true,
    error: "",
  },
  {
    id: "profileSedcondName",
    name: "second_name",
    label: "Фамилия",
    placeholder: "Введите фамилию",
    type: "text",
    required: true,
    disabled: true,
    error: "",
  },
  {
    id: "profileDisplayName",
    name: "display_name",
    label: "Имя в чате",
    placeholder: "Введите имя в чате",
    type: "text",
    required: true,
    disabled: true,
    error: "",
  },
  {
    id: "profilePhoneName",
    name: "phone",
    label: "Телефон",
    placeholder: "Введите телефон",
    type: "tel",
    required: true,
    disabled: true,
    error: "",
  },
];
