export const REGISTRATION_SETTINGS = [
  {
    id: "registrationEmail",
    name: "email",
    label: "Почта",
    placeholder: "Введите адрес",
    type: "text",
    required: true,
    error: "Зполните поле",
  },
  {
    id: "registrationLogin",
    name: "login",
    label: "Логин",
    placeholder: "Введите логин",
    type: "text",
    required: true,
    error: "Зполните поле",
  },
  {
    id: "registrationFirstName",
    name: "first_name",
    label: "Имя",
    placeholder: "Введите имя",
    type: "text",
    required: true,
    error: "Зполните поле",
  },
  {
    id: "registrationLastName",
    name: "last_name",
    label: "Фамилия",
    placeholder: "Введите фамилию",
    type: "text",
    required: true,
    error: "Зполните поле",
  },
  {
    id: "registrationPhone",
    name: "phone",
    label: "Телефон",
    placeholder: "+7 XXX XXX-XX-XX",
    type: "text",
    required: true,
    error: "Зполните поле",
  },
  {
    id: "registrationPassword",
    name: "password",
    label: "Телефон",
    placeholder: "Введите пароль",
    type: "password",
    required: true,
    error: "",
  },
  {
    id: "registrationPasswordConfirm",
    name: "password_confirm",
    label: "Телефон",
    placeholder: "Введите пароль",
    type: "password",
    required: true,
    error: "Пароли не совпадают",
  },
];
